export const environment = {
  production: true,
  api_auth: 'https://ws-produccion-auth.turismo.gob.ec/',
  api_dinardap: 'https://ws-produccion-dinardap.turismo.gob.ec/',
  api_consultor: 'https://ws-produccion-consultor.turismo.gob.ec/',
  api_exporter: 'https://ws-produccion-exporter.turismo.gob.ec/',
  api_base: 'https://ws-produccion-base.turismo.gob.ec/',
  api_alojamiento: 'https://ws-produccion-alojamiento.turismo.gob.ec/',
  api_financiero: 'https://ws-produccion-financiero.turismo.gob.ec/',
  api_mailer: 'https://ws-produccion-mailer.turismo.gob.ec/',
  api_catastro: 'https://ws-produccion-catastro.turismo.gob.ec/',
  api_alimentosbebidas: 'https://ws-produccion-alimentos.turismo.gob.ec/',
  api_gad: 'https://ws-produccion-gad.turismo.gob.ec/',
  gmapapiKey: 'AIzaSyCGUwCcM-LKjRK4rjbBJ06_GLmX2LaYzfg',
};
